name: IzaManagement CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: bcmath, ctype, fileinfo, json, mbstring, openssl, pdo, tokenizer, xml, pdo_pgsql, dom, gd, soap, intl, zip, redis

    - name: Copy .env file
      # Copiem explicit din subfolderul unde știm că se află fișierul
      run: cp IzaMedApp/.env.production IzaMedApp/.env

    - name: Install Composer Dependencies
      # Rulăm comanda specificând directorul de lucru
      working-directory: ./IzaMedApp
      run: composer install --prefer-dist --no-progress

    - name: Install Node.js dependencies
      working-directory: ./IzaMedApp
      run: npm install

    - name: Build frontend assets
      working-directory: ./IzaMedApp
      run: npm run build

    - name: Run Laravel Tests
      working-directory: ./IzaMedApp
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: |
        php artisan key:generate
        touch database/database.sqlite
        php artisan migrate --force
        vendor/bin/phpunit
