name: Symfony CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # --- PASUL 1: Setarea fișierului .env ---
    # Copiem fișierul .env.test, deoarece acesta este mediul de testare
    - name: Create .env file
      run: cp .env.test .env

    # --- PASUL 2: Instalarea dependențelor PHP ---
    - name: Install Composer Dependencies
      run: composer install --prefer-dist --no-progress

    # --- PASUL 3: Instalarea dependențelor Node.js și compilarea asset-urilor ---
    - name: Install Node.js dependencies
      run: npm install

    - name: Build frontend assets
      run: npm run build

    # --- PASUL 4: Crearea bazei de date și rularea testelor ---
    - name: Create Database and Schema
      run: |
        php bin/console doctrine:database:create --env=test
        php bin/console doctrine:schema:create --env=test

    - name: Run Tests (PHPUnit)
      run: php bin/phpunit
