name: Symfony Project CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Pasul 1: Clonează codul în directorul de lucru
      - name: Checkout code
        uses: actions/checkout@v3

      # Pasul 2: Setează mediul de testare folosind secrete
      # Asigurați-vă că ați creat secretul 'DOT_ENV_TEST' în setările repository-ului
      - name: Create .env file for testing
        run: echo "${{ secrets.DOT_ENV_TEST }}" > .env
      
      # Pasul 3: Instalează dependențele PHP
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      # Pasul 4: Instalează dependențele Node.js
      - name: Install Node.js dependencies
        run: npm install

      # Pasul 5: Compilează asset-urile frontend
      - name: Build frontend assets
        run: npm run build

      # Pasul 6: Pregătește baza de date pentru teste
      # Folosim --env=test pentru a ne asigura că se folosesc setările din .env
      - name: Setup Test Database
        run: |
          php bin/console doctrine:database:create --if-not-exists --env=test
          php bin/console doctrine:schema:create --env=test

      # Pasul 7: Rulează testele
      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit
