name: IzaManagement CI Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    name: Run Laravel Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: bcmath, ctype, fileinfo, json, mbstring, openssl, pdo, tokenizer, xml, pdo_pgsql, dom, gd, soap, intl, zip, redis
        coverage: none

    - name: Copy .env
      # Copiem explicit din subfolderul IzaMedApp în rădăcina de lucru a pasului următor
      run: cp $GITHUB_WORKSPACE/IzaMedApp/.env.production $GITHUB_WORKSPACE/IzaMedApp/.env

    - name: Install Composer Dependencies
      # Rulăm comanda specificând calea către subfolder
      working-directory: ./IzaMedApp
      run: composer update --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate Application Key
      working-directory: ./IzaMedApp
      run: php artisan key:generate

    - name: Create SQLite Database
      working-directory: ./IzaMedApp
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Execute Tests (PHPUnit)
      working-directory: ./IzaMedApp
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite # Calea este acum relativă la working-directory
      run: vendor/bin/phpunit
