name: IzaManagement CI Tests

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    name: Run Laravel Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup PHP with Extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: bcmath, ctype, fileinfo, json, mbstring, openssl, pdo, tokenizer, xml, pdo_pgsql, dom, gd, soap, intl, zip, redis
        coverage: none

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.production', '.env');"

    - name: Install Composer Dependencies
      # Folosim 'update' pentru a genera un composer.lock nou, compatibil cu mediul de CI
      run: composer update --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Create SQLite Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Execute Tests (PHPUnit)
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: ${{ github.workspace }}/database/database.sqlite
      run: vendor/bin/phpunit
