name: IzaManagement Laravel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    name: Build and Test in Subfolder
    runs-on: ubuntu-latest
    
    steps:
    # 1. Descarcă codul
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Setează mediul PHP
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: bcmath, ctype, fileinfo, json, mbstring, openssl, pdo, tokenizer, xml, pdo_pgsql, dom, gd, soap, intl, zip, redis

    # 3. Copiază fișierul .env explicit
    - name: Create .env file
      run: cp IzaMedApp/.env.production IzaMedApp/.env

    # 4. Instalează dependențele Composer specificând calea
    - name: Install Composer Dependencies
      run: composer install --prefer-dist --no-progress --no-scripts -d ./IzaMedApp

    # 5. Instalează dependențele Node.js specificând calea
    - name: Install Node.js Dependencies
      run: npm install --prefix ./IzaMedApp
    
    # 6. Compilează asset-urile frontend specificând calea
    - name: Build Frontend Assets
      run: npm run build --prefix ./IzaMedApp
      
    # 7. Rulează testele Laravel
    - name: Run Laravel Tests
      # Schimbăm directorul de lucru doar pentru acest pas complex
      working-directory: ./IzaMedApp
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: |
        php artisan key:generate
        touch database/database.sqlite
        php artisan migrate --force
        vendor/bin/phpunit
