name: Symfony Project CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Pasul 1: Clonează repository-ul
    - name: Checkout code
      uses: actions/checkout@v3

    # Pasul 2: Creează fișierul .env.test din secret
    # Asigurați-vă că ați creat secretul 'DOT_ENV_TEST' în setările repository-ului
    - name: Create .env.test file
      run: echo "${{ secrets.DOT_ENV_TEST }}" > .env.test
      shell: bash

    # Pasul 3: Copiază fișierul de test în .env pentru a fi folosit de Symfony
    - name: Copy .env.test to .env
      run: cp .env.test .env
      shell: bash

    # Pasul 4: Instalează dependențele PHP cu Composer
    - name: Install Composer Dependencies
      run: composer install --prefer-dist --no-progress --no-scripts

    # Pasul 5: Instalează dependențele Node.js
    - name: Install Node.js Dependencies
      run: npm install

    # Pasul 6: Compilează asset-urile frontend
    - name: Build Frontend Assets
      run: npm run build

    # Pasul 7: Pregătește baza de date de testare
    - name: Create Database and Schema
      run: |
        php bin/console doctrine:database:create --env=test
        php bin/console doctrine:schema:create --env=test
      
    # Pasul 8: Rulează testele PHPUnit
    - name: Execute Tests (PHPUnit)
      run: ./vendor/bin/phpunit
