name: IzaManagement Laravel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    name: Build and Test Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: bcmath, ctype, fileinfo, json, mbstring, openssl, pdo, tokenizer, xml, pdo_pgsql, dom, gd, soap, intl, zip, redis

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create .env from .env.production
        run: |
          echo "Creating .env file from .env.production..."
          cp .env.production .env

      - name: Install Composer deps
        run: composer install --prefer-dist --no-progress --no-scripts --no-interaction

      - name: Install Node deps & build frontend
        run: |
          npm ci
          npm run build

      - name: Prepare DB & Run Tests
        run: |
          php artisan key:generate
          touch database/database.sqlite
          php artisan migrate --force
          vendor/bin/phpunit --stop-on-failure
