name: IzaManagement Laravel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    name: Build and Test Laravel Application
    runs-on: ubuntu-latest
    
    steps:
    # 1. Descarcă codul
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Setează mediul PHP
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: bcmath, ctype, fileinfo, json, mbstring, openssl, pdo, tokenizer, xml, pdo_pgsql, dom, gd, soap, intl, zip, redis

    # 3. Muta-te în directorul proiectului și rulează toate comenzile de acolo
    - name: Run all commands within the project directory
      # Specificăm directorul de lucru pentru acest pas complex
      working-directory: ./IzaMedApp
      run: |
        # Pasul A: Copiază fișierul .env
        echo "Creating .env file..."
        cp .env.production .env
        
        # Pasul B: Instalează dependențele Composer
        echo "Installing Composer dependencies..."
        composer install --prefer-dist --no-progress --no-scripts
        
        # Pasul C: Instalează dependențele Node.js
        echo "Installing Node.js dependencies..."
        npm install
        
        # Pasul D: Compilează asset-urile frontend
        echo "Building frontend assets..."
        npm run build
        
        # Pasul E: Pregătește baza de date și rulează testele
        echo "Running Laravel tests..."
        php artisan key:generate
        touch database/database.sqlite
        php artisan migrate --force
        vendor/bin/phpunit
