name: IzaManagement Laravel CI - Final Attempt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    name: Build and Test Application
    runs-on: ubuntu-latest
    
    steps:
    # 1. Descarcă codul
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Setează mediul PHP
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: bcmath, ctype, fileinfo, json, mbstring, openssl, pdo, tokenizer, xml, pdo_pgsql, dom, gd, soap, intl, zip, redis

    # 3. Afișează structura de fișiere pentru depanare
    - name: List files in workspace
      run: ls -R

    # 4. Copiază .env
    - name: Create .env file
      run: cp IzaMedApp/.env.production IzaMedApp/.env

    # 5. Instalează dependențele Composer
    - name: Install Composer Dependencies
      run: composer install --prefer-dist --no-progress --no-scripts -d IzaMedApp/
      
    # 6. Instalează dependențele Node.js
    - name: Install Node.js dependencies
      run: npm install --prefix IzaMedApp/

    # 7. Compilează asset-urile
    - name: Build frontend assets
      run: npm run build --prefix IzaMedApp/

    # 8. Rulează testele Laravel
    - name: Run Laravel Tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: IzaMedApp/database/database.sqlite
      run: |
        cd IzaMedApp
        php artisan key:generate
        touch database/database.sqlite
        php artisan migrate --force
        vendor/bin/phpunit
