name: Test IzaMedApp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files
        run: ls -la && ls -la resources/js

      - name: Install Node.js dependencies
        working-directory: ./resources/js
        run: npm install

      - name: Build frontend
        working-directory: ./resources/js
        run: npm run build

      - name: Validate Docker Compose
        run: docker-compose config
